### PR TITLE
nix: Use stdenv without CC on macOS

### PR DESCRIPTION
**Pull request by phlmn**
Actually not sure if this is a good idea...

### CODE REVIEW

**Comment by anuejn** [comment]
still does not work for me :/

**Comment by pajowu** [comment]
Doesn't this just cause the build system to use the compiler provided by mac os (if no compiler is configured in the nix system packages?)

**Comment by anuejn** [comment]
Can we close this @phlmn

**Comment by pajowu** [comment]
Closing as it seems to be fixed with #77

**Pull request closed without merging**
