### PR TITLE
👷 Cache pypackages in ci

### PR DESCRIPTION
**Pull request by pajowu**

### CODE REVIEW

**Comment by anuejn** [comment]
what kind of rust stuff are we building in the ci?

**Comment by pajowu** [comment]
automerge. My hope is that this would make the macos build less flaky. I don't fully understand why it breaks sometimes yet. Seems like somehow cargo sometimes fails to find the correct commit???

**Comment by anuejn** [comment]
would't be the better approach to build wheels for our automerge bindings?

**Comment by pajowu** [comment]
Maybe. My hope was that this give a good-enough hotfix until the automerge developers release a new version with the fixes so we can just switch back to upsteam

**Comment by anuejn** [comment]
fair :D

**Review by anuejn — APPROVED** [review]

**Pull request merged**
