### PR TITLE
📖 use openapi schema for frontend <-> backend communication

### PR DESCRIPTION
**Pull request by anuejn**

### CODE REVIEW

**Comment by anuejn** [comment]
@phlmn is it done from your side? If so, I would rebase it (combine some commits) and then merge it?

**Comment by anuejn** [comment]
Somehow the types are... Unimpressive and don't really work for me. I think this needs some more work

**Comment by phlmn** [comment]
> Somehow the types are... Unimpressive and don't really work for me. I think this needs some more work

What does not work for you?

**Comment by anuejn** [comment]
Okay no, I was just wrong. Reloading vscode helped 🙈

**Review by phlmn — APPROVED** [review]

**Pull request merged**
